-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 15:02:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja_sql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_sql` DEFAULT CHARACTER SET utf8mb4 ;
USE `loja_sql` ;

-- -----------------------------------------------------
-- Table `loja_sql`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_sql`.`estado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NULL DEFAULT NULL,
  `UF` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `loja_sql`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_sql`.`municipio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Estado_ID` INT NOT NULL,
  `Nome` VARCHAR(80) NULL DEFAULT NULL,
  `CodIBGE` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Municipio_Estado1_idx` (`Estado_ID` ASC),
  CONSTRAINT `fk_Municipio_Estado1`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `loja_sql`.`estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `loja_sql`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_sql`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `celular` CHAR(11) NULL DEFAULT NULL,
  `EndLogradouro` VARCHAR(100) NOT NULL,
  `EndNumero` VARCHAR(10) NOT NULL,
  `EndMunicipio` INT NOT NULL,
  `EndCep` CHAR(8) NULL DEFAULT NULL,
  `Municipio_ID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Municipio1_idx` (`Municipio_ID` ASC),
  CONSTRAINT `fk_Cliente_Municipio1`
    FOREIGN KEY (`Municipio_ID`)
    REFERENCES `loja_sql`.`municipio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `loja_sql`.`contareceber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_sql`.`contareceber` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Cliente_ID` INT NOT NULL,
  `FaturaVendaId` INT NULL DEFAULT NULL,
  `DataConta` DATE NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Valor` DECIMAL(18,2) NULL DEFAULT NULL,
  `Situação` ENUM('1', '2', '3') NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ContaReceber_Cliente_idx` (`Cliente_ID`),
  CONSTRAINT `fk_ContaReceber_Cliente`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `loja_sql`.`cliente` (`id`)
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
